InstagramApp/CommandPanel/Controllers/AccountMainPageController.cs
using System.Web.Mvc;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class AccountMainPageController : Controller
    {
        private readonly AccountService accountService;

        public AccountMainPageController()
        {
            this.accountService = new AccountService();
        }

        // GET: AccountMainPage
        public ActionResult Index(AccountName accountId)
        {
            var model = accountService.GetAccountMainStatistic(accountId);

            return View(model);
        }

        public ActionResult ClearAllUsersToFollow(AccountName accountId)
        {
            accountService.RemoveAllUsersToFollow(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ClearAllUsersToDelete(AccountName accountId)
        {
            accountService.RemoveAllUsersToDelete(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ClearAllNormalUsers(AccountName accountId)
        {
            accountService.RemoveAllNormalUsers(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult SwitchFunctionalityAccess(AccountName accountId, FunctionalityName functionalityName)
        {
            accountService.SwitchFunctionalityAccess(accountId, functionalityName);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult SetFunctionalityAsAsap(AccountName accountId, FunctionalityName functionalityName)
        {
            accountService.SetFunctionalityAsAsap(accountId, functionalityName);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ClearLogs(AccountName accountId)
        {
            accountService.ClearAccountLogs(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ResetAllSearchFriendsMarks(AccountName accountId)
        {
            accountService.ResetAllSearchFriendsMarks(accountId);
            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ResetAllFunctionalityTokens(AccountName accountId)
        {
            accountService.ResetAllFunctionalityTokens(accountId);
            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult MakeFunctionalityReport(AccountName accountId)
        {
            accountService.MakeFunctionalityReport(accountId);
            return RedirectToAction("Index", new { accountId = accountId });
        }
    }
}

InstagramApp/CommandPanel/Controllers/ConfigurationsController.cs
using System.Web.Mvc;
using CommandPanel.Models.ConfigurationsModels;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class ConfigurationsController : Controller
    {
        private readonly ConfigurationsService configurationsService;

        public ConfigurationsController()
        {
            this.configurationsService = new ConfigurationsService();
        }

        // GET: Configurations
        public ActionResult Index(AccountName accountId)
        {
            var settings = configurationsService.GetConfigurations(accountId);
            return View(settings);
        }

        public ActionResult UpdateSettings(AccountName accountId, ConfigurationsDraftModel model)
        {
            configurationsService.UpdateConfigurations(accountId, model);
            return RedirectToAction("Index", new { accountId = accountId });
        }
    }
}

InstagramApp/CommandPanel/Controllers/ContentDataController.cs
using System.Web.Mvc;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class ContentDataController : Controller
    {
        private readonly ContentService contentService;

        public ContentDataController()
        {
            this.contentService = new ContentService();
        }

        // GET: Content
        public ActionResult Index(AccountName accountId)
        {
            var list = contentService.GetAddedContent(accountId);
            return View(list);
        }
    }
}

InstagramApp/CommandPanel/Controllers/HashTagController.cs
using System.Web.Mvc;
using CommandPanel.Models.HashTagModels;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class HashTagController : Controller
    {
        private readonly HashTagService hashTagService;

        public HashTagController()
        {
            this.hashTagService = new HashTagService();
        }

        // GET: HashTag
        public ActionResult Index(AccountName accountId)
        {
            var models = hashTagService.GetHashTags(accountId);
            var result = new HashTagListViewModel
            {
                HashTags = models,
                AccountId = accountId
            };
            return View(result);
        }

        public ActionResult RemoveHashTage(AccountName accountId, string hashTag)
        {
            hashTagService.RemoveHashTag(accountId, hashTag);
            return RedirectToAction("Index", new {accountId});
        }

        [HttpPost]
        public ActionResult AddHashTag(AccountName accountId, string hashTag)
        {
            hashTagService.AddHashTag(accountId, hashTag);
            return RedirectToAction("Index", new {accountId});
        }
    }
}

InstagramApp/CommandPanel/Controllers/LanguageController.cs
using System.Web.Mvc;
using CommandPanel.Models.LanguageModels;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class LanguageController : Controller
    {
        private readonly LanguageService languageService;

        public LanguageController()
        {
            this.languageService = new LanguageService();
        }

        // GET: Language
        public ActionResult Index(AccountName accountId)
        {
            var models = languageService.GetLanguages(accountId);
            var result = new LanguageListViewModel
            {
                Languages = models,
                AccountId = accountId
            };
            return View(result);
        }

        public ActionResult RemoveLanguage(AccountName accountId, string language)
        {
            languageService.RemoveLanguage(accountId, language);
            return RedirectToAction("Index", new { accountId });
        }

        [HttpPost]
        public ActionResult AddLanguage(AccountName accountId, string language)
        {
            languageService.AddLanguage(accountId, language);
            return RedirectToAction("Index", new { accountId });
        }
    }
}

InstagramApp/CommandPanel/Views/AccountMainPage/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model CommandPanel.Models.AccountModels.AccountMainStatisticViewModel

@section scripts
{
    <script src="http://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script type="text/javascript">

        $(function() {
            $(".deleteButton").click(function(e) {
                e.preventDefault();
                $.get(this.href, function(data) {
                    $('#modDialog').modal('show');
                });
                $("#no").click(function() {
                    location.reload();
                });
            });
        });

        $(function() {
            $(".deleteButton2").click(function(e) {
                e.preventDefault();
                $.get(this.href, function(data) {
                    $('#modDialog2').modal('show');
                });
                $("#no2").click(function() {
                    location.reload();
                });
            });
        });

        $(function() {
            $(".deleteButton3").click(function(e) {
                e.preventDefault();
                $.get(this.href, function(data) {
                    $('#modDialog3').modal('show');
                });
                $("#no3").click(function() {
                    location.reload();
                });
            });
        });

        $(function() {
            $(".deleteButton4").click(function(e) {
                e.preventDefault();
                $.get(this.href, function(data) {
                    $('#modDialog4').modal('show');
                });
                $("#no4").click(function() {
                    location.reload();
                });
            });
        });
    </script>

    <script type="text/javascript">

        window.onload = function () {

            var list = @( Html.Raw(Model.ChartJsonData) );
            var data = list.map(function(v) {
                return {
                    x: new Date(v.Year, v.Month, v.Day),
                    y: v.Value
                }
            });

            var chart = new CanvasJS.Chart("chartContainer",
            {
                title: {
                    text: "Followers statistic"
                },
                axisY :{
                    includeZero: false
                },
                data: [
                    {
                        type: "spline",

                        dataPoints: data
                    }
                ]
            });

            chart.render();
        }
    </script>
}

<div class="row">

    <h2>@Model.AccountId.ToString("G") <a href="@Model.PageLink" target="_blank">(Link)</a></h2>

    <div class="head-panel">
        <div class="boxes">
            <div class="followers-box">
                <div>Followers count:</div>
                <div class="followers-count">@Model.FollowersCount</div>
                <div>Date: @Model.LastStatisticDate</div>
            </div>

            <div class="followers-box">
                <div>Followings count:</div>
                <div class="followers-count">@Model.FollowingsCount</div>
                <div>Date: @Model.LastStatisticDate</div>
            </div>

            <div class="followers-box">
                <div>Media count:</div>
                <div class="followers-count">@Model.MediaCount</div>
                <div>Date: @Model.LastStatisticDate</div>
            </div>
        </div>

        <div class="center-space">
            <div class="followers-box">
                <div>Users to follow count:</div>
                <div class="followers-count">@Model.UsersToFollowCount</div>
            </div>

            <div class="followers-box">
                <div>Users to delete count:</div>
                <div class="followers-count">@Model.UsersToDeleteCount</div>
            </div>

            <div class="followers-box">
                <div>Normal users count: </div>
                <div class="followers-count">@Model.NormalUsersCount</div>
            </div>
        </div>
        <div class="chart-box">
            <div id="chartContainer"></div>
        </div>
    </div>

    <div class="lists-section">
        <div class="buttons-list">
            <a href="@Url.Action("Index", "HashTag", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Hash tags </a>
            <a href="@Url.Action("Index", "ContentData", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Content </a>
            <a href="@Url.Action("Index", "Language", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Language </a>
            <a href="@Url.Action("Index", "ImportantUsers", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Important users </a>
            <a href="@Url.Action("Index", "Configurations", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Configurations </a>
            <a href="@Url.Action("Index", "Bases", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Bases </a>
            <a class="btn btn-primary action-button deleteButton"> Remove all users to follow </a>
            <a class="btn btn-primary action-button deleteButton2"> Remove all users to delete </a>
            <a class="btn btn-primary action-button deleteButton3"> Remove all normal users</a>
            <a class="btn btn-primary action-button deleteButton4"> Clear logs</a>
            <a href="@Url.Action("ResetAllSearchFriendsMarks", "AccountMainPage", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Reset search marks </a>
            <a href="@Url.Action("ResetAllFunctionalityTokens", "AccountMainPage", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Reset functionality tokens </a>
            <a href="@Url.Action("MakeFunctionalityReport", "AccountMainPage", new {accountId = Model.AccountId})" class="btn btn-primary action-button"> Make functionality report </a>
        </div>

        <div class="center-data">
            <div>
                <div class="inner-box">
                    <div>
                        <h2>Common information</h2>
                    </div>
                    <div>
                        First report: @Model.Info.FirstReportDate (@Model.Info.FirstReportFollowersCount Followers)
                    </div>
                    <div class="bottom-line">
                        <h3>Bases</h3>
                        @foreach (var baseData in @Model.Info.Bases)
                        {
                            <div>
                                @baseData.BaseLink
                            </div>
                        }
                    </div>
                    <div class="bottom-line">
                        <h3>Succeed actions per day (@Model.DaylyFunctionalityReport.StartDate.ToString("d"))</h3>
                        <div>
                            <ul>
                                @foreach (var record in @Model.DaylyFunctionalityReport.Records)
                                {
                                    <li>
                                        @record.FunctionalityName: @record.Successed
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>    
            </div>
            <div>
                @if (Model.FunctionalityReport != null)
                {
                    <div class="inner-box">
                        <div>
                            <h2>Last report</h2>
                        </div>
                        <div>
                            <h4>Start date: <span class="followers-count">@Model.FunctionalityReport.StartDate</span></h4>
                        </div>
                        <div>
                            <h4>End date: <span class="followers-count">@Model.FunctionalityReport.EndDate</span></h4>
                        </div>

                        <br/>

                        @foreach (var record in @Model.FunctionalityReport.Records)
                        {
                            <div class="inline-box box200">
                                <div>
                                    <b>@record.FunctionalityName</b>
                                </div>
                                <div>Cancelled: @record.Cancelled</div>
                                <div>Exceptions: @record.Exceptions</div>
                                <div>Successed: @record.Successed</div>
                                <div>Started: @record.Started</div>
                                <br/>
                            </div>
                        }
                    </div>
                }
            </div>
        </div>

        <div class="functionality-section alert alert-primary">
            @foreach (var functionality in @Model.Functionalities)
            {
                <div class="functionality-line alert alert-primary">
                    <div class="inline-box">
                        <a href="@Url.Action("SwitchFunctionalityAccess", "AccountMainPage", new { accountId = Model.AccountId, functionalityName = functionality.FunctionalityName })" class="no-line-link">
                            @if (functionality.Stopped)
                            {
                                <div class="red-circle"> ! </div>
                            }
                            else if (functionality.IsActive)
                            {
                                <div class="green-box"></div>
                            }
                            else
                            {
                                <div class="blue-box"></div>
                            }
                        </a>
                    </div>
                    <div class="inline-box">
                        <span>@functionality.FunctionalityName.ToString("G")</span> <br />
                        <span>@functionality.LastActivation.Day.ToString("D2").@functionality.LastActivation.Month.ToString("D2") @functionality.LastActivation.Hour.ToString("D2"):@functionality.LastActivation.Minute.ToString("D2")</span>
                    </div>
                    @if (functionality.Asap)
                    {
                        <div class="inline-box asap pull-right">
                            ASAP!
                        </div>
                    }
                    else
                    {
                        <div class="inline-box no-asap pull-right">
                            <a href="@Url.Action("SetFunctionalityAsAsap", "AccountMainPage", new { accountId = Model.AccountId, functionalityName = functionality.FunctionalityName })">Make it ASAP.</a>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog">
        <div class="modal-header"> Are you sure you want to clear database? </div>
        <div class="modal-buttons">
            <a class="btn btn-primary" id="no">No</a>
            <a href="@Url.Action("ClearAllUsersToFollow", "AccountMainPage", new {accountId = Model.AccountId})" class="btn btn-primary">Yes</a>
        </div>
    </div>
</div>

<div id="modDialog2" class="modal fade">
    <div id="dialogContent2" class="modal-dialog">
        <div class="modal-header"> Are you sure you want to clear database? </div>
        <div class="modal-buttons">
            <a class="btn btn-primary" id="no2">No</a>
            <a href="@Url.Action("ClearAllUsersToDelete", "AccountMainPage", new {accountId = Model.AccountId})" class="btn btn-primary">Yes</a>
        </div>
    </div>
</div>

<div id="modDialog3" class="modal fade">
    <div id="dialogContent3" class="modal-dialog">
        <div class="modal-header"> Are you sure you want to clear database? </div>
        <div class="modal-buttons">
            <a class="btn btn-primary" id="no3">No</a>
            <a href="@Url.Action("ClearAllNormalUsers", "AccountMainPage", new {accountId = Model.AccountId})" class="btn btn-primary">Yes</a>
        </div>
    </div>
</div>

<div id="modDialog4" class="modal fade">
    <div id="dialogContent4" class="modal-dialog">
        <div class="modal-header"> Are you sure you want to clear database? </div>
        <div class="modal-buttons">
            <a class="btn btn-primary" id="no4">No</a>
            <a href="@Url.Action("ClearLogs", "AccountMainPage", new { accountId = Model.AccountId })" class="btn btn-primary">Yes</a>
        </div>
    </div>
</div>