InstagramApp/CommandPanel/Models/ImportantUserModels/ImportantUserViewModel.cs
namespace CommandPanel.Models.ImportantUserModels
{
    public class ImportantUserViewModel
    {
        public string UserLink { get; set; }
    }
}

InstagramApp/CommandPanel/Controllers/ImportantUsersController.cs
using System.Web.Mvc;
using CommandPanel.Models.ImportantUserModels;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class ImportantUsersController : Controller
    {
        private readonly ImportantUsersService importantUsersService;

        public ImportantUsersController()
        {
            this.importantUsersService = new ImportantUsersService();
        }

        // GET: ImportantUsers
        public ActionResult Index(AccountName accountId)
        {
            var models = importantUsersService.GetImportantUsers(accountId);
            var result = new ImportantUserListViewModel
            {
                Users = models,
                AccountId = accountId
            };
            return View(result);
        }

        public ActionResult RemoveImportantUser(AccountName accountId, string user)
        {
            importantUsersService.RemoveImportantUser(accountId, user);
            return RedirectToAction("Index", new { accountId });
        }

        [HttpPost]
        public ActionResult AddImportantUser(AccountName accountId, string user)
        {
            importantUsersService.AddImportantUser(accountId, user);
            return RedirectToAction("Index", new { accountId });
        }
    }
}

InstagramApp/CommandPanel/Views/ImportantUsers/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model CommandPanel.Models.ImportantUserModels.ImportantUserListViewModel

<div class="row">
    @using (Html.BeginForm("AddImportantUser", "ImportantUsers", FormMethod.Post))
    {
        <input type="hidden" name="accountId" value="@Model.AccountId" />

        <div class="input-hashtag ">
            <div>
                <input type="text" name="user" class="form-control" />
            </div>
            <input type="submit" value="Send word" class="btn btn-primary" />
        </div>
    }
</div>

@foreach (var user in @Model.Users)
{
    <div class="alert-info alert"> <span>@user.UserLink</span> <a href="@Url.Action("RemoveImportantUser", "ImportantUsers", new { accountId = @Model.AccountId, user = user.UserLink })" class="btn btn-danger pull-right">Remove</a> </div>
}