InstagramApp/CommandPanel/Controllers/AccountMainPageController.cs
using System.Web.Mvc;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class AccountMainPageController : Controller
    {
        private readonly AccountService accountService;

        public AccountMainPageController()
        {
            this.accountService = new AccountService();
        }

        // GET: AccountMainPage
        public ActionResult Index(AccountName accountId)
        {
            var model = accountService.GetAccountMainStatistic(accountId);

            return View(model);
        }

        public ActionResult ClearAllUsersToFollow(AccountName accountId)
        {
            accountService.RemoveAllUsersToFollow(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ClearAllUsersToDelete(AccountName accountId)
        {
            accountService.RemoveAllUsersToDelete(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ClearAllNormalUsers(AccountName accountId)
        {
            accountService.RemoveAllNormalUsers(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult SwitchFunctionalityAccess(AccountName accountId, FunctionalityName functionalityName)
        {
            accountService.SwitchFunctionalityAccess(accountId, functionalityName);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult SetFunctionalityAsAsap(AccountName accountId, FunctionalityName functionalityName)
        {
            accountService.SetFunctionalityAsAsap(accountId, functionalityName);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ClearLogs(AccountName accountId)
        {
            accountService.ClearAccountLogs(accountId);

            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ResetAllSearchFriendsMarks(AccountName accountId)
        {
            accountService.ResetAllSearchFriendsMarks(accountId);
            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult ResetAllFunctionalityTokens(AccountName accountId)
        {
            accountService.ResetAllFunctionalityTokens(accountId);
            return RedirectToAction("Index", new { accountId = accountId });
        }

        public ActionResult MakeFunctionalityReport(AccountName accountId)
        {
            accountService.MakeFunctionalityReport(accountId);
            return RedirectToAction("Index", new { accountId = accountId });
        }
    }
}

InstagramApp/CommandPanel/Controllers/BotController.cs
using System.Web.Mvc;
using CommandPanel.Models.ConfigurationsModels;
using CommandPanel.Services;
using Constants;

namespace CommandPanel.Controllers
{
    public class BotController : Controller
    {
        private readonly BotService botService;

        public BotController()
        {
            this.botService = new BotService();
        }

        // GET: Bot
        public ActionResult Index()
        {
            var bots = botService.GetConfigurations();
            return View(bots);
        }

        public ActionResult UpdateSettings(AccountName accountId, ConfigurationsDraftModel model)
        {
            botService.UpdateConfigurations(accountId, model);
            return RedirectToAction("Index", new { accountId = accountId });
        }
    }
}

InstagramApp/CommandPanel/Controllers/HomeController.cs
using System.Web.Mvc;
using CommandPanel.Services;

namespace CommandPanel.Controllers
{
    public class HomeController : Controller
    {
        private readonly HomeService homeService;

        public HomeController()
        {
            this.homeService = new HomeService();
        }

        public ActionResult Index()
        {
            var result = homeService.GetAccountList();
            return View(result);
        }
    }
}

InstagramApp/CommandPanel/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@model List<CommandPanel.Models.HomeModels.AccountViewModel>

<div class="row">
    <div>
        <a href="@Url.Action("Index", "Bot")" class="btn btn-primary pull-right">Go to bots</a>
    </div>
</div>

<hr />

<div class="row">

    @foreach (var account in Model)
    {
        <a href="@Url.Action("Index", "AccountMainPage", new {accountId = account.AccountId})" class="no-line-link">
            <div class="panel panel-primary account-list-line">
                <div class="panel-body">@account.Name</div>
            </div>
        </a>
        <hr />
        <span><a href="@account.Url" target="_blank">@account.Url</a></span>
        <hr />
        <span> Proxy Name: @account.ProxyLogin</span>
        <br />
        <span> Proxy Password: @account.ProxyPassword</span>
        <hr />
        <span>
            @if (account.Followers > 10000)
            {
                <span class="green-bold">Followers: @account.Followers </span>
            }
            else
            {
                <span>Followers: @account.Followers </span>
            }
            
            @if (account.Difference <= 0)
            {
                <span class="red-bold">(@account.Difference)</span>
            }
            else
            {
                if (account.Difference > 20)
                {
                    <span class="green-bold">(+@account.Difference)</span>
                }
                else
                {
                    <span>(+@account.Difference)</span>
                }
            }
        </span>
        <br />
        if (account.Following > 2500 && account.Following < 6500)
        {
            <span> Following: @account.Following </span>
        }
        else
        {
            <span class="red-bold"> Following: @account.Following</span>
        }
        <br />
        if (account.UsersToFollow < 12000)
        {
            <span class="red-bold"> Base: @account.UsersToFollow</span>
        }
        else
        {
            if (account.UsersToFollow > 35000)
            {
                <span class="green-bold"> Base: @account.UsersToFollow</span>
            }
            else
            {
                <span> Base: @account.UsersToFollow</span>
            }
        }
        <hr />
        <br />
        <br />
        <br />
        <br />
    }

</div>